### ISSUE TITLE
 An idea which will simplify global_vars editing in customize.yml

### ISSUE THREAD

**Issue by Sudokamikaze** [jlund/streisand-discussions#144]
Hi there! First of all, I want to say thank you. You've made awesome project!

I'm sure that you know about that. But I wanna hear your opinion

And here's my idea:
`customize.yml` uses `lineinfile` method and there's some lines with that. 

We can simplify variable editing by using Jinja templates!
Here's example of code which will be in `customize.yml`

```
  tasks:
    - template:
        src: /templates/vars.yml.j2 
        dest: /global_vars/vars.yml  
```

Parameters will fill these brackets {{ }} in template file after copying.

If you would agree with that I would do pull request with good commit description

What do you think?
